# =====================================================================
#  Gnominium Chunk Viewer  -  asset scanner
# ---------------------------------------------------------------------
#  Scans assets\{tiles,walls,glass,sprites} for .png files, reads each
#  one's size, base64-embeds it, and writes assets.js .  The page loads
#  assets.js with a plain <script> tag, so the whole tool runs by just
#  double-clicking index.html  -  no web server, no CORS headaches.
#
#  DROP-IN WORKFLOW
#    * new floor tile   -> assets\tiles   named  <set>-<variant>.png
#    * new wall theme   -> assets\walls   named  <theme>-<role>.png
#    * new glass pane   -> assets\glass   any name.png (64x64)
#    * new sprite/decor -> assets\sprites any name.png
#  ...then re-run this script (or double-click scan-assets.bat).
#
#  Wall <role> is the text after the FIRST dash, e.g.
#    overworldWall1-top_cap.png      -> theme "overworldWall1", role "top_cap"
#  Recognised roles are listed in main.js (AUTOTILE table). "01"/"02"
#  are treated as the plain / isolated block.
# =====================================================================

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$assetsDir = Join-Path $root 'assets'

function Read-PngSize([byte[]]$b) {
    # PNG IHDR: width = bytes 16..19, height = 20..23, big-endian
    if ($b.Length -lt 24) { return @{ w = 0; h = 0 } }
    $w = ([int]$b[16] -shl 24) -bor ([int]$b[17] -shl 16) -bor ([int]$b[18] -shl 8) -bor [int]$b[19]
    $h = ([int]$b[20] -shl 24) -bor ([int]$b[21] -shl 16) -bor ([int]$b[22] -shl 8) -bor [int]$b[23]
    return @{ w = $w; h = $h }
}

function Load-Png([System.IO.FileInfo]$f) {
    $bytes = [System.IO.File]::ReadAllBytes($f.FullName)
    $size  = Read-PngSize $bytes
    $b64   = [System.Convert]::ToBase64String($bytes)
    return [ordered]@{
        name = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
        w    = $size.w
        h    = $size.h
        src  = "data:image/png;base64,$b64"
    }
}

function Get-Pngs([string]$sub) {
    $dir = Join-Path $assetsDir $sub
    if (-not (Test-Path $dir)) { return @() }
    Get-ChildItem -Path $dir -Filter *.png -File | Sort-Object Name
}

# ---- tiles: grouped into "sets" by the text before the first dash ----
$tilesetMap = [ordered]@{}
foreach ($f in Get-Pngs 'tiles') {
    $img = Load-Png $f
    $dash = $img.name.IndexOf('-')
    $set  = if ($dash -ge 0) { $img.name.Substring(0, $dash) } else { $img.name }
    if (-not $tilesetMap.Contains($set)) { $tilesetMap[$set] = New-Object System.Collections.ArrayList }
    [void]$tilesetMap[$set].Add($img)
}
$tilesets = @()
foreach ($k in $tilesetMap.Keys) { $tilesets += [ordered]@{ name = $k; variants = @($tilesetMap[$k]) } }

# ---- walls: grouped into "themes"; role = text after the first dash ----
$wallThemeMap = [ordered]@{}
foreach ($f in Get-Pngs 'walls') {
    $img  = Load-Png $f
    $dash = $img.name.IndexOf('-')
    if ($dash -lt 0) { continue }
    $theme = $img.name.Substring(0, $dash)
    $role  = $img.name.Substring($dash + 1)
    if (-not $wallThemeMap.Contains($theme)) { $wallThemeMap[$theme] = [ordered]@{} }
    $wallThemeMap[$theme][$role] = [ordered]@{ w = $img.w; h = $img.h; src = $img.src }
}
$wallsets = @()
foreach ($k in $wallThemeMap.Keys) { $wallsets += [ordered]@{ name = $k; roles = $wallThemeMap[$k] } }

# ---- glass + sprites: flat lists ----
$glass   = @(Get-Pngs 'glass'   | ForEach-Object { Load-Png $_ })
$sprites = @(Get-Pngs 'sprites' | ForEach-Object { Load-Png $_ })

$payload = [ordered]@{
    generated = (Get-Date).ToString('s')
    tilesets  = $tilesets
    wallsets  = $wallsets
    glass     = $glass
    sprites   = $sprites
}

$json = $payload | ConvertTo-Json -Depth 12 -Compress
$outPath = Join-Path $root 'assets.js'
$header  = "// AUTO-GENERATED by scan-assets.ps1 on $((Get-Date).ToString('s')). Do not edit by hand.`r`n"
$body    = "window.GNOM_ASSETS = $json;`r`n"
[System.IO.File]::WriteAllText($outPath, $header + $body, [System.Text.Encoding]::UTF8)

Write-Host ("Wrote {0}" -f $outPath)
Write-Host ("  tilesets : {0}" -f (($tilesets  | ForEach-Object { '{0}({1})' -f $_.name, $_.variants.Count }) -join ', '))
Write-Host ("  wallsets : {0}" -f (($wallsets  | ForEach-Object { '{0}({1} roles)' -f $_.name, $_.roles.Count }) -join ', '))
Write-Host ("  glass    : {0}" -f $glass.Count)
Write-Host ("  sprites  : {0}" -f $sprites.Count)
